version: "3.7"

services:
  Python:
    entrypoint:
    - sleep
    - infinity
    platform: linux/amd64
    image: python:3.10
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock